version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"  # Expose your Node.js app on port 3000
    environment:
      - REDIS_HOST=redis  # Set the hostname of the Redis service

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"  # Expose the Redis port
